version: '3.8'
services:
    redis:
        image: redis/redis-stack-server:latest
        container_name: redis_server
        ports:
            - '6379:6379'
        env_file:
            - .env
        networks:
            - app_network
    app:
        build: ./
        ports:
            - '8082:8082'
        depends_on:
            - redis
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
