services:
    - name: mongodb
      type: background
      env: docker
      plan: starter
      docker:
          image: mongo:4.4
          command: ['mongod', '--bind_ip', '0.0.0.0']
      mounts:
          - path: /docker-entrypoint-initdb.d
            volume: database-dump
      regions:
          - oregon

    - name: mongo-import
      type: background
      env: docker
      plan: starter
      docker:
          image: mongo:4.4
          command: |
              sh -c "
                sleep 20 &&
                mongoimport --host mongodb --db Tiktok --collection users --file /data/Tiktok.users.json --jsonArray &&
                mongoimport --host mongodb --db Tiktok --collection videos --file /data/Tiktok.videos.json --jsonArray &&
                mongoimport --host mongodb --db Tiktok --collection reactions --file /data/Tiktok.reactions.json --jsonArray &&
                mongoimport --host mongodb --db Tiktok --collection hashtags --file /data/Tiktok.hashtags.json --jsonArray &&
                mongoimport --host mongodb --db Tiktok --collection Follows --file /data/Tiktok.Follows.json --jsonArray &&
                mongoimport --host mongodb --db Tiktok --collection comments --file /data/Tiktok.comments.json --jsonArray"
      mounts:
          - path: /data
            volume: database-dump
      dependsOn:
          - mongodb
      regions:
          - oregon

    - name: redis
      type: background
      env: docker
      plan: starter
      docker:
          image: redis:latest
          command: ['redis-server', '--bind', '0.0.0.0', '--port', '6379']
      regions:
          - oregon

    - name: tiktok-app
      type: web
      env: docker
      plan: starter
      docker:
          image: your-dockerhub-username/your-app-image:latest
      envVars:
          - key: PORT
            value: 8082
          - key: REDIS_URL
            value: redis://redis:6379
          - key: MONGO_URL
            value: mongodb://mongodb:27017/Tiktok
      regions:
          - oregon

volumes:
    - name: database-dump
      mountPath: /docker-entrypoint-initdb.d
